project_name: mittnite
before:
  hooks:
    - go mod download
    - go test ./...

builds:
  - &defaultBuild
    id: mittnite
    binary: mittnite
    main: main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mittwald/mittnite/cmd.Version={{ .Version }} -X github.com/mittwald/mittnite/cmd.Commit={{ .Commit }} -X github.com/mittwald/mittnite/cmd.BuiltAt={{ .Date }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
  - <<: *defaultBuild
    id: mittnitectl
    binary: mittnitectl
    main: ./cmd/mittnitectl
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "Linux" }}linux
      {{- if eq .Os "Darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq  .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}
      {{ end -}}
    files:
      - LICENSE
nfpms:
  - vendor: Mittwald CM Service
    homepage: https://github.com/mittwald/mittnite
    maintainer: Martin Helmich <m.helmich@mittwald.de>
    description: Smart and small init system for containers
    license: Proprietary
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - dst: /etc/mittnite.d
        type: dir
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
    -
      image_templates:
        - quay.io/mittwald/mittnite:v{{ .Major }}
        - quay.io/mittwald/mittnite:v{{ .Major }}.{{ .Minor }}
        - quay.io/mittwald/mittnite:{{ .Tag }}
        - quay.io/mittwald/mittnite:stable
        - quay.io/mittwald/mittnite:latest
        - quay.io/mittwald/mittnite:v{{ .Major }}-alpine
        - quay.io/mittwald/mittnite:v{{ .Major }}.{{ .Minor }}-alpine
        - quay.io/mittwald/mittnite:{{ .Tag }}-alpine
        - quay.io/mittwald/mittnite:stable-alpine
      goos: linux
      goarch: amd64
      goarm: ''
